name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest app.py

      - name: Build and deploy
        uses: docker/build-push-action@v2
          context: .
          push: true
          tags: my-pipeline/app:latest